# Generated by Django 4.0.7 on 2024-01-09 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Motoboy',
                'verbose_name_plural': 'Motoboys',
                'ordering': ('name',),
            },
        ),
    ]
